apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/giantswarm/hello-world-app
      path: helm/hello-world
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/infra/gitops/local/apps/business/hello-world/values.yaml

    - repoURL: https://github.com/aymene01/atlas.git
      targetRevision: main
      ref: values

  destination:
    namespace: hello-world
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true